-- Name:        habamax
-- Description: Hubba hubba hubba.
-- Author:      Maxim Kim <habamax@gmail.com>
-- Maintainer:  Maxim Kim <habamax@gmail.com>
-- Website:     https://github.com/vim/colorschemes
-- License:     Same as Vim
-- Last Change: 2025 Jan 07

-- Generated by Colortemplate v2.2.3 (re-written and fixed in Lua, re-written by Gemini 2.5 flash)
local cmd, fn, g, o, api = vim.cmd, vim.fn, vim.g, vim.o, vim.api

o.background = 'dark'
cmd('hi clear')
cmd('source $VIMRUNTIME/colors/vim.lua')
g.colors_name = 'habamax-plus'

if fn.exists('syntax_on') then
    cmd('syntax reset')
end

local colors = {
    black = '#1c1c1c',
    black_234 = 234,
    gray = '#9e9e9e',
    gray_247 = 247,
    darkgray = '#767676',
    darkgray_243 = 243,
    darkred = '#af5f5f',
    darkred_131 = 131,
    red = '#d75f87',
    red_168 = 168,
    darkgreen = '#5faf5f',
    darkgreen_71 = 71,
    green = '#87d787',
    green_114 = 114,
    darkyellow = '#af875f',
    darkyellow_137 = 137,
    yellow = '#d7af87',
    yellow_180 = 180,
    darkblue = '#5f87af',
    darkblue_67 = 67,
    blue = '#5fafd7',
    blue_74 = 74,
    darkmagenta = '#af87af',
    darkmagenta_139 = 139,
    magenta = '#d787d7',
    magenta_176 = 176,
    darkcyan = '#5f8787',
    darkcyan_66 = 66,
    cyan = '#87afaf',
    cyan_109 = 109,
    white = '#bcbcbc',
    white_250 = 250,
    line = '#303030',
    line_236 = 236,
    pmenu_bg = '#3a3a3a',
    pmenu_bg_237 = 237,
    folded = '#262626',
    folded_235 = 235,
    nont_key = '#585858',
    nont_key_240 = 240,
    search_highlight = '#ffaf5f',
    search_highlight_215 = 215,
    cursorline_nr = '#dadada',
    cursorline_nr_253 = 253,
    cursor_l = '#5fff00',
    cursor_l_82 = 82,
    match_paren = '#ff00af',
    match_paren_199 = 199,
    removed = '#d75f5f',
    removed_167 = 167,
    added = '#5fd75f',
    added_77 = 77,
}

local M = {
    colors = colors,
}

-- Helper function to define highlight groups
local function hi(group, props)
    api.nvim_set_hl(0, group, props)
end

local function setup_highlights()
    -- Link common highlight groups
    cmd('hi! link Terminal Normal')
    cmd('hi! link StatuslineTerm Statusline')
    cmd('hi! link StatuslineTermNC StatuslineNC')
    cmd('hi! link MessageWindow Pmenu')
    cmd('hi! link PopupSelected PmenuSel')
    cmd('hi! link javaScriptFunction Statement')
    cmd('hi! link javaScriptIdentifier Statement')
    cmd('hi! link sqlKeyword Statement')
    cmd('hi! link yamlBlockMappingKey Statement')
    cmd('hi! link rubyMacro Statement')
    cmd('hi! link rubyDefine Statement')
    cmd('hi! link vimVar Normal')
    cmd('hi! link vimOper Normal')
    cmd('hi! link vimSep Normal')
    cmd('hi! link vimParenSep Normal')
    cmd('hi! link vimCommentString Comment')
    cmd('hi! link markdownUrl String')

    -- True Color / GUI
    if o.termguicolors or g.gui_running then
        g.terminal_ansi_colors = {
            colors.black,
            colors.darkred,
            colors.darkgreen,
            colors.darkyellow,
            colors.darkblue,
            colors.darkmagenta,
            colors.darkcyan,
            colors.gray,
            colors.darkgray,
            colors.red,
            colors.green,
            colors.yellow,
            colors.blue,
            colors.magenta,
            colors.cyan,
            colors.white,
        }
        for i, color in ipairs(g.terminal_ansi_colors) do
            g['terminal_color_' .. i - 1] = color
        end

        hi('Normal', { fg = colors.white, bg = colors.black })
        hi('Statusline', { fg = colors.black, bg = colors.gray })
        hi('StatuslineNC', { fg = colors.black, bg = colors.darkgray })
        -- CHANGE: bg darkgray to black
        hi('VertSplit', { fg = colors.darkgray, bg = colors.black })
        hi('TabLine', { fg = colors.black, bg = colors.darkgray })
        hi('TabLineFill', { fg = colors.black, bg = colors.darkgray })
        hi('TabLineSel', { fg = colors.black, bg = colors.gray, bold = true })
        hi('ToolbarLine', { fg = 'NONE', bg = 'NONE' })
        hi('ToolbarButton', { fg = colors.darkgray, bg = colors.black, bold = true, reverse = true })
        hi('QuickFixLine', { fg = colors.black, bg = colors.darkblue })
        hi('CursorLineNr', { fg = colors.cursorline_nr, bold = true })
        hi('LineNr', { fg = colors.nont_key })
        hi('LineNrAbove', { fg = colors.nont_key })
        hi('LineNrBelow', { fg = colors.nont_key })
        hi('NonText', { fg = colors.nont_key })
        hi('EndOfBuffer', { fg = colors.nont_key })
        hi('SpecialKey', { fg = colors.nont_key })
        hi('FoldColumn', { fg = colors.nont_key })
        hi('Visual', { fg = colors.cyan, bg = colors.black, reverse = true })
        hi('VisualNOS', { fg = colors.black, bg = colors.darkcyan })
        hi('Pmenu', { bg = colors.pmenu_bg })
        hi('PmenuThumb', { bg = colors.darkgray })
        hi('PmenuSbar', { fg = 'NONE', bg = 'NONE' })
        hi('PmenuSel', { bg = colors.nont_key })
        hi('PmenuKind', { fg = colors.darkcyan, bg = colors.pmenu_bg })
        hi('PmenuKindSel', { fg = colors.darkcyan, bg = colors.nont_key })
        hi('PmenuExtra', { fg = colors.darkgray, bg = colors.pmenu_bg })
        hi('PmenuExtraSel', { fg = colors.gray, bg = colors.nont_key })
        hi('PmenuMatch', { fg = colors.search_highlight, bg = colors.pmenu_bg })
        hi('PmenuMatchSel', { fg = colors.search_highlight, bg = colors.nont_key })
        hi('SignColumn', { fg = 'NONE', bg = 'NONE' })
        hi('Error', { fg = colors.darkred, bg = colors.black, reverse = true })
        hi('ErrorMsg', { fg = colors.darkred, bg = colors.black, reverse = true })
        hi('ModeMsg', { bold = true })
        hi('MoreMsg', { fg = colors.darkgreen })
        hi('Question', { fg = colors.yellow })
        hi('WarningMsg', { fg = colors.red })
        hi('Todo', { fg = colors.cursorline_nr, bold = true })
        hi('MatchParen', { fg = colors.match_paren, bold = true })
        hi('Search', { fg = colors.blue, bg = colors.black, reverse = true })
        hi('IncSearch', { fg = colors.search_highlight, bg = colors.black, reverse = true })
        hi('CurSearch', { fg = colors.search_highlight, bg = colors.black, reverse = true })
        hi('WildMenu', { fg = colors.black, bg = colors.yellow, bold = true })
        hi('debugPC', { fg = colors.black, bg = colors.darkblue })
        hi('debugBreakpoint', { fg = colors.black, bg = colors.red })
        hi('Cursor', { fg = '#000000', bg = colors.cursorline_nr })
        hi('lCursor', { fg = colors.black, bg = colors.cursor_l })
        hi('CursorLine', { bg = colors.line })
        hi('CursorColumn', { bg = colors.line })
        hi('Folded', { fg = colors.gray, bg = colors.folded })
        hi('ColorColumn', { bg = colors.pmenu_bg })
        hi('SpellBad', { sp = colors.removed, undercurl = true })
        hi('SpellCap', { sp = colors.search_highlight, undercurl = true })
        hi('SpellLocal', { sp = colors.added, undercurl = true })
        hi('SpellRare', { sp = colors.magenta, undercurl = true })
        hi('Comment', { fg = colors.darkgray })
        hi('Constant', { fg = colors.red })
        hi('String', { fg = colors.darkgreen })
        hi('Character', { fg = colors.green })
        hi('Identifier', { fg = colors.cyan })
        hi('Statement', { fg = colors.darkmagenta })
        hi('PreProc', { fg = colors.darkyellow })
        hi('Type', { fg = colors.darkblue })
        hi('Special', { fg = colors.darkcyan })
        hi('Underlined', { underline = true })
        hi('Title', { bold = true })
        hi('Directory', { fg = colors.cyan, bold = true })
        hi('Conceal', { fg = colors.nont_key })
        hi('Ignore', {})
        hi('Debug', { fg = colors.darkcyan })

        -- CHANGE: remove reverse for Diffxxx
        hi('DiffAdd', { fg = colors.darkgreen })
        hi('DiffChange', { fg = colors.darkblue })
        hi('DiffText', { fg = colors.darkmagenta })
        hi('DiffDelete', { fg = colors.darkred })

        -- END OF CHANGE

        hi('Added', { fg = colors.added })
        hi('Changed', { fg = colors.search_highlight })
        hi('Removed', { fg = colors.removed })

    -- 256 colors
    else
        g.terminal_ansi_colors = {
            colors.black_234,
            colors.darkred_131,
            colors.darkgreen_71,
            colors.darkyellow_137,
            colors.darkblue_67,
            colors.darkmagenta_139,
            colors.darkcyan_66,
            colors.gray_247,
            colors.darkgray_243,
            colors.red_168,
            colors.green_114,
            colors.yellow_180,
            colors.blue_74,
            colors.magenta_176,
            colors.cyan_109,
            colors.white_250,
        }
        for i, color in ipairs(g.terminal_ansi_colors) do
            g['terminal_color_' .. i - 1] = color
        end

        hi('Normal', { ctermfg = colors.white_250, ctermbg = colors.black_234 })
        hi('Statusline', { ctermfg = colors.black_234, ctermbg = colors.gray_247 })
        hi('StatuslineNC', { ctermfg = colors.black_234, ctermbg = colors.darkgray_243 })
        hi('VertSplit', { ctermfg = colors.darkgray_243, ctermbg = colors.darkgray_243 })
        hi('TabLine', { ctermfg = colors.black_234, ctermbg = colors.darkgray_243 })
        hi('TabLineFill', { ctermfg = colors.black_234, ctermbg = colors.darkgray_243 })
        hi('TabLineSel', { ctermfg = colors.black_234, ctermbg = colors.gray_247, bold = true })
        hi('ToolbarLine', { ctermfg = 'NONE', ctermbg = 'NONE' })
        hi('ToolbarButton', { ctermfg = colors.darkgray_243, ctermbg = colors.black_234, bold = true, reverse = true })
        hi('QuickFixLine', { ctermfg = colors.black_234, ctermbg = colors.darkblue_67 })
        hi('CursorLineNr', { ctermfg = colors.cursorline_nr_253, bold = true })
        hi('LineNr', { ctermfg = colors.nont_key_240 })
        hi('LineNrAbove', { ctermfg = colors.nont_key_240 })
        hi('LineNrBelow', { ctermfg = colors.nont_key_240 })
        hi('NonText', { ctermfg = colors.nont_key_240 })
        hi('EndOfBuffer', { ctermfg = colors.nont_key_240 })
        hi('SpecialKey', { ctermfg = colors.nont_key_240 })
        hi('FoldColumn', { ctermfg = colors.nont_key_240 })
        hi('Visual', { ctermfg = colors.cyan_109, ctermbg = colors.black_234, reverse = true })
        hi('VisualNOS', { ctermfg = colors.black_234, ctermbg = colors.darkcyan_66 })
        hi('Pmenu', { ctermbg = colors.pmenu_bg_237 })
        hi('PmenuThumb', { ctermbg = colors.darkgray_243 })
        hi('PmenuSbar', { ctermfg = 'NONE', ctermbg = 'NONE' })
        hi('PmenuSel', { ctermbg = colors.nont_key_240 })
        hi('PmenuKind', { ctermfg = colors.darkcyan_66, ctermbg = colors.pmenu_bg_237 })
        hi('PmenuKindSel', { ctermfg = colors.darkcyan_66, ctermbg = colors.nont_key_240 })
        hi('PmenuExtra', { ctermfg = colors.darkgray_243, ctermbg = colors.pmenu_bg_237 })
        hi('PmenuExtraSel', { ctermfg = colors.gray_247, ctermbg = colors.nont_key_240 })
        hi('PmenuMatch', { ctermfg = colors.search_highlight_215, ctermbg = colors.pmenu_bg_237 })
        hi('PmenuMatchSel', { ctermfg = colors.search_highlight_215, ctermbg = colors.nont_key_240 })
        hi('SignColumn', { ctermfg = 'NONE', ctermbg = 'NONE' })
        hi('Error', { ctermfg = colors.darkred_131, ctermbg = colors.black_234, reverse = true })
        hi('ErrorMsg', { ctermfg = colors.darkred_131, ctermbg = colors.black_234, reverse = true })
        hi('ModeMsg', { bold = true })
        hi('MoreMsg', { ctermfg = colors.darkgreen_71 })
        hi('Question', { ctermfg = colors.yellow_180 })
        hi('WarningMsg', { ctermfg = colors.red_168 })
        hi('Todo', { ctermfg = colors.cursorline_nr_253, bold = true })
        hi('MatchParen', { ctermfg = colors.match_paren_199, bold = true })
        hi('Search', { ctermfg = colors.blue_74, ctermbg = colors.black_234, reverse = true })
        hi('IncSearch', { ctermfg = colors.search_highlight_215, ctermbg = colors.black_234, reverse = true })
        hi('CurSearch', { ctermfg = colors.search_highlight_215, ctermbg = colors.black_234, reverse = true })
        hi('WildMenu', { ctermfg = colors.black_234, ctermbg = colors.yellow_180, bold = true })
        hi('debugPC', { ctermfg = colors.black_234, ctermbg = colors.darkblue_67 })
        hi('debugBreakpoint', { ctermfg = colors.black_234, ctermbg = colors.red_168 })
        hi('Cursor', { ctermfg = 0, ctermbg = colors.cursorline_nr_253 })
        hi('lCursor', { ctermfg = colors.black_234, ctermbg = colors.cursor_l_82 })
        hi('CursorLine', { ctermbg = colors.line_236 })
        hi('CursorColumn', { ctermbg = colors.line_236 })
        hi('Folded', { ctermfg = colors.gray_247, ctermbg = colors.folded_235 })
        hi('ColorColumn', { ctermbg = colors.pmenu_bg_237 })
        hi('SpellBad', { ctermfg = colors.removed_167, underline = true })
        hi('SpellCap', { ctermfg = colors.search_highlight_215, underline = true })
        hi('SpellLocal', { ctermfg = colors.added_77, underline = true })
        hi('SpellRare', { ctermfg = colors.magenta_176, underline = true })
        hi('Comment', { ctermfg = colors.darkgray_243 })
        hi('Constant', { ctermfg = colors.red_168 })
        hi('String', { ctermfg = colors.darkgreen_71 })
        hi('Character', { ctermfg = colors.green_114 })
        hi('Identifier', { ctermfg = colors.cyan_109 })
        hi('Statement', { ctermfg = colors.darkmagenta_139 })
        hi('PreProc', { ctermfg = colors.darkyellow_137 })
        hi('Type', { ctermfg = colors.darkblue_67 })
        hi('Special', { ctermfg = colors.darkcyan_66 })
        hi('Underlined', { underline = true })
        hi('Title', { bold = true })
        hi('Directory', { ctermfg = colors.cyan_109, bold = true })
        hi('Conceal', { ctermfg = colors.nont_key_240 })
        hi('Ignore', {})
        hi('Debug', { ctermfg = colors.darkcyan_66 })
        hi('DiffAdd', { ctermfg = colors.darkgreen_71, reverse = true })
        hi('DiffChange', { ctermfg = colors.darkblue_67, reverse = true })
        hi('DiffText', { ctermfg = colors.darkmagenta_139, reverse = true })
        hi('DiffDelete', { ctermfg = colors.darkred_131, reverse = true })
        hi('Added', { ctermfg = colors.added_77 })
        hi('Changed', { ctermfg = colors.search_highlight_215 })
        hi('Removed', { ctermfg = colors.removed_167 })

        -- 16 colors
        -- else
        --     hi('Normal', { ctermfg = 'white', ctermbg = 'black' })
        --     hi('Statusline', { ctermfg = 'black', ctermbg = 'gray' })
        --     hi('StatuslineNC', { ctermfg = 'black', ctermbg = 'darkgray' })
        --     hi('VertSplit', { ctermfg = 'darkgray', ctermbg = 'darkgray' })
        --     hi('TabLine', { ctermfg = 'black', ctermbg = 'darkgray' })
        --     hi('TabLineFill', { ctermfg = 'black', ctermbg = 'darkgray' })
        --     hi('TabLineSel', { ctermfg = 'black', ctermbg = 'gray', bold = true })
        --     hi('ToolbarLine', { ctermfg = 'NONE', ctermbg = 'NONE' })
        --     hi('ToolbarButton', { ctermfg = 'darkgray', ctermbg = 'black', bold = true, reverse = true })
        --     hi('QuickFixLine', { ctermfg = 'black', ctermbg = 'darkblue' })
        --     hi('CursorLineNr', { ctermfg = 'white', bold = true })
        --     hi('LineNr', { ctermfg = 'darkgrey' })
        --     hi('LineNrAbove', { ctermfg = 'darkgrey' })
        --     hi('LineNrBelow', { ctermfg = 'darkgrey' })
        --     hi('NonText', { ctermfg = 'darkgrey' })
        --     hi('EndOfBuffer', { ctermfg = 'darkgrey' })
        --     hi('SpecialKey', { ctermfg = 'darkgrey' })
        --     hi('FoldColumn', { ctermfg = 'darkgrey' })
        --     hi('Visual', { ctermfg = 'cyan', ctermbg = 'black', reverse = true })
        --     hi('VisualNOS', { ctermfg = 'black', ctermbg = 'darkcyan' })
        --     hi('Pmenu', { ctermfg = 'black', ctermbg = 'gray' })
        --     hi('PmenuThumb', { ctermfg = 'gray', ctermbg = 'black' })
        --     hi('PmenuSbar', { ctermfg = 'NONE', ctermbg = 'gray' })
        --     hi('PmenuSel', { ctermfg = 'black', ctermbg = 'darkyellow' })
        --     hi('PmenuKind', { ctermfg = 'darkred', ctermbg = 'gray' })
        --     hi('PmenuKindSel', { ctermfg = 'darkred', ctermbg = 'darkyellow' })
        --     hi('PmenuExtra', { ctermfg = 'darkgray', ctermbg = 'gray' })
        --     hi('PmenuExtraSel', { ctermfg = 'black', ctermbg = 'darkyellow' })
        --     hi('PmenuMatch', { ctermfg = 'black', ctermbg = 'gray', bold = true })
        --     hi('PmenuMatchSel', { ctermfg = 'black', ctermbg = 'darkyellow', bold = true })
        --     hi('SignColumn', { ctermfg = 'NONE', ctermbg = 'NONE' })
        --     hi('Error', { ctermfg = 'darkred', ctermbg = 'black', reverse = true })
        --     hi('ErrorMsg', { ctermfg = 'darkred', ctermbg = 'black', reverse = true })
        --     hi('ModeMsg', { bold = true })
        --     hi('MoreMsg', { ctermfg = 'darkgreen' })
        --     hi('Question', { ctermfg = 'yellow' })
        --     hi('WarningMsg', { ctermfg = 'red' })
        --     hi('Todo', { ctermfg = 'white', bold = true })
        --     hi('MatchParen', { ctermfg = 'magenta', bold = true })
        --     hi('Search', { ctermfg = 'blue', ctermbg = 'black', reverse = true })
        --     hi('IncSearch', { ctermfg = 'red', ctermbg = 'black', reverse = true })
        --     hi('CurSearch', { ctermfg = 'red', ctermbg = 'black', reverse = true })
        --     hi('WildMenu', { ctermfg = 'black', ctermbg = 'yellow', bold = true })
        --     hi('debugPC', { ctermfg = 'black', ctermbg = 'darkblue' })
        --     hi('debugBreakpoint', { ctermfg = 'black', ctermbg = 'red' })
        --     hi('CursorLine', { underline = true })
        --     hi('CursorColumn', { ctermfg = 'black', ctermbg = 'darkyellow' })
        --     hi('Folded', { ctermfg = 'black', ctermbg = 'darkyellow' })
        --     hi('ColorColumn', { ctermfg = 'black', ctermbg = 'darkyellow' })
        --     hi('SpellBad', { ctermfg = 'darkred', underline = true })
        --     hi('SpellCap', { ctermfg = 'darkyellow', underline = true })
        --     hi('SpellLocal', { ctermfg = 'darkgreen', underline = true })
        --     hi('SpellRare', { ctermfg = 'magenta', underline = true })
        --     hi('Comment', { ctermfg = 'darkgray' })
        --     hi('Constant', { ctermfg = 'red' })
        --     hi('String', { ctermfg = 'darkgreen' })
        --     hi('Character', { ctermfg = 'green' })
        --     hi('Identifier', { ctermfg = 'cyan' })
        --     hi('Statement', { ctermfg = 'darkmagenta' })
        --     hi('PreProc', { ctermfg = 'darkyellow' })
        --     hi('Type', { ctermfg = 'darkblue' })
        --     hi('Special', { ctermfg = 'darkcyan' })
        --     hi('Underlined', { underline = true })
        --     hi('Title', { bold = true })
        --     hi('Directory', { ctermfg = 'cyan', bold = true })
        --     hi('Conceal', { ctermfg = 'darkgrey' })
        --     hi('Ignore', {})
        --     hi('Debug', { ctermfg = 'darkcyan' })
        --     hi('DiffAdd', { ctermfg = 'darkgreen', reverse = true })
        --     hi('DiffChange', { ctermfg = 'darkblue', reverse = true })
        --     hi('DiffText', { ctermfg = 'darkmagenta', reverse = true })
        --     hi('DiffDelete', { ctermfg = 'darkred', reverse = true })
        --     hi('Added', { ctermfg = 'darkgreen' })
        --     hi('Changed', { ctermfg = 'darkyellow' })
        --     hi('Removed', { ctermfg = 'darkred' })
    end
end

setup_highlights()

return M
