vim.wo.number = true
vim.wo.relativenumber = true
vim.wo.scrolloff = 5
vim.wo.signcolumn = "yes"
vim.bo.undofile = true
vim.bo.tabstop = 2
vim.bo.shiftwidth = 2
vim.bo.softtabstop = 2
vim.bo.expandtab = true
vim.bo.swapfile = false
vim.bo.autoindent = true
vim.bo.syntax = "on"
-- vim.bo.fileencodings = "utf-8,gb2312,gbk,gb18030"
-- vim.bo.encoding = "utf-8"
vim.o.mouse = "a"
vim.o.undofile = true
vim.o.tabstop = 2
vim.o.shiftwidth = 2
vim.o.softtabstop = 2
vim.o.expandtab = true
vim.o.autowrite = true
vim.o.swapfile = false
vim.o.hlsearch = true
vim.o.ignorecase = true
vim.o.smartcase = true
vim.o.backup = false
vim.o.autochdir = true
vim.o.autoindent = true
vim.o.history = 400
vim.o.fileencodings = "utf-8,gb2312,gbk,gb18030"
vim.o.encoding = "utf-8"
vim.o.syntax = "on"
vim.o.hidden = true
vim.o.writebackup = true
--vim.cmd("set undodir=~/.config/nvim/undodir")

